name: CI Workflow

on:
  pull_request:
    types:
      - synchronize
      - closed
    branches:
      - develop

env:
  ACCESS_TOKEN: ${{ secrets.MY_PERSONAL_ACCESS_TOKEN }}
  API_URL: 'https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/reviews'
  API_HEADERS: "-H 'Authorization: Bearer ${{ secrets.MY_PERSONAL_ACCESS_TOKEN}}' -H 'Accept: application/vnd.github+json'"

jobs:
  dismiss-approvals:
    name: Dismiss Approvals
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Source get from https://docs.github.com/ko/rest/pulls/reviews?apiVersion=2022-11-28#dismiss-a-review-for-a-pull-request
      - name: Dismiss Approvals
        run: |
          REVIEW_IDS=$(curl -L -s ${{env.API_HEADERS}} "${{env.API_URL}}" | jq '.[] | select(.state == "APPROVED") | .id')
          for id in $REVIEW_IDS; do
            curl -L -X PUT ${{env.API_HEADERS}} "${{env.API_URL}}/${id}/dismissals" -d '{"message":"You are dismissed","event":"DISMISS"}'
          done

  validate-approvals:
    name: Validate Approvals
    runs-on: ubuntu-latest
    needs: dismiss-approvals

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # 새로운 커밋에 대해 승인 상태 확인
      - name: Check for Approval
        id: check_approval
        run: |
          API_URL="https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/reviews"
          APPROVAL_COUNT=$(curl -L -s -H "Authorization: Bearer ${{ env.ACCESS_TOKEN }}" -H "Accept: application/vnd.github+json" "$API_URL" | jq '[.[] | select(.state == "APPROVED")] | length')
          if [ "$APPROVAL_COUNT" -lt 1 ]; then
            echo "Two approvals are required before merging to develop branch."
            exit 1
          else
            echo "Two approvals received. Ready for merge."
          fi
