name: Delete Branch
on:
  push:
    branches:
      - develop

jobs:
  delete-branches:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/develop'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get Remote Branches to Delete
        id: get_branches
        run: |
          BRANCHES=$(curl -s -H "Authorization: Bearer ${{ secrets.MY_PERSONAL_ACCESS_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          "https://api.github.com/repos/${{ github.repository }}/branches" \
          | jq -r '.[] | .name')

          echo "Branches: $BRANCHES"
      shell: bash

      # - name: Delete Branches
      #   run: |
      #     for branch in ${{ steps.get_branches.outputs.branches }}; do
      #       echo "Deleting branch: $branch"
      #       git push origin --delete $branch
      #     done
