name: CD Workflow

on:
  push:
    branches-ignore:
      - main
      - develop

jobs:
  delete-branch:
    name: Delete Merged Branch
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Delete Branch
        run: |
          BRANCH_NAME=$(echo "${{ github.ref }}" | sed -e "s/refs\/heads\///")
          echo "deleted ${BRANCH_NAME}"
          git push origin --delete "$BRANCH_NAME"
