name: Delete Branch
on:
  push:
    branches:
      - develop

jobs:
  delete-branches:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/develop'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get Remote Branches to Delete
        id: get_branches
        run: |
          BRANCHES=$(curl -s -H "Authorization: Bearer ${{ secrets.MY_PERSONAL_ACCESS_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/${{ github.repository }}/branches" \
            | jq -r '.[] | .name' | grep -E "^(feature/|refactor/|issue/)")


          if [ -n "$BRANCHES" ]; then
            echo "The list of Branches will be deleted: $BRANCHES"

            for branch in $BRANCHES; do
              echo "Deleting branch: $branch"
              curl -X DELETE -H "Authorization: Bearer ${{ secrets.MY_PERSONAL_ACCESS_TOKEN }}" \
                "https://api.github.com/repos/${{ github.repository }}/git/refs/heads/$branch"
            done
          else
            echo "No branches to delete."
          fi
        shell: bash
