name: Delete Branch
on:
  push:
    branches:
      - develop

jobs:
  delete-branches:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Delete Branches
        run: |
          # 원하는 브랜치 패턴에 따라 브랜치 삭제 작업 수행
          BRANCHES_TO_DELETE=$(git branch | grep -E "^(feature/|refactor/|issue/)")
          for branch in $BRANCHES_TO_DELETE; do
            echo "Deleting branch: $branch"
            curl -X DELETE \
              -H "Authorization: Bearer ${{ secrets.MY_PERSONAL_ACCESS_TOKEN }}" \
              "https://api.github.com/repos/${{ github.repository }}/git/refs/heads/$branch"
          done
