name: Delete Branch
on:
  push:
    branches:
      - develop

jobs:
  delete-branches:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Delete Branches
        run: |
          # 원하는 브랜치 패턴에 따라 브랜치 삭제 작업 수행
          for branch in $(git branch | grep -E "^(feature/|refactor/|issue/)"); do
            git push origin --delete "$branch"
          done
