name: Delete Stale Branches

on:
  push:
    branches:
      - develop

env:
  API_HEADERS: "-H 'Authorization: Bearer ${{ secrets.MY_PERSONAL_ACCESS_TOKEN }}'"

jobs:
  delete-stale-branches:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/develop'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

        # Source get from https://docs.github.com/en/free-pro-team@latest/rest/branches/branches?apiVersion=2022-11-28#list-branches
        # Get the list of remote branches that match the specified patterns

        # Source get from https://docs.github.com/en/rest/git/refs?apiVersion=2022-11-28#get-a-reference
        # Delete the remote branch
      - name: Get Remote Branches to Delete
        id: get_branches
        run: |
          BRANCHES=$(curl -s ${{env.API_HEADERS}} \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/${{ github.repository }}/branches" \
            | jq -r '.[] | .name')

          echo $BRANCHES

          if [ -z "$BRANCHES" ]; then
            echo "No branches to delete."
            exit 0
          fi

          echo "The list of Branches will be deleted: $BRANCHES"

          for branch in $BRANCHES; do
            echo "Deleting branch: $branch"

            curl -X DELETE ${{env.API_HEADERS}} \
              "https://api.github.com/repos/${{ github.repository }}/git/refs/heads/$branch"
          done
        shell: bash
