name: Delete Branch
on:
  push:
    branches:
      - develop

jobs:
  delete-branches:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/develop'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get Remote Branches to Delete
        id: get_branches
        run: |
          BRANCHES_TO_DELETE=$(git ls-remote --heads origin | grep -E "^(refs/heads/feature/|refs/heads/refactor/|refs/heads/issue/)" | sed -E 's/.*\///')
          echo "Branches to delete: $BRANCHES_TO_DELETE"
          echo "::set-output name=branches::$BRANCHES_TO_DELETE"

      - name: Delete Branches
        run: |
          for branch in ${{ steps.get_branches.outputs.branches }}; do
            echo "Deleting branch: $branch"
            git push origin --delete $branch
          done
