name: Delete Branch
on:
  push:
    branches:
      - develop

jobs:
  delete-branches:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Delete Branches
        run: |
          # 현재 브랜치 가져오기
          CURRENT_BRANCH=$(git branch --show-current)

          # main 브랜치와 develop 브랜치는 삭제하지 않음
          if [ "$CURRENT_BRANCH" != "main" ] && [ "$CURRENT_BRANCH" != "develop" ]; then
            # 원하는 브랜치 패턴에 따라 브랜치 삭제 작업 수행
            git push origin --delete "$CURRENT_BRANCH"
          else
            echo "Skipping deletion of $CURRENT_BRANCH"
          fi
