name: Auto Update PR Body
on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  update_pr_body:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Update PR List Body
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.MY_PERSONAL_ACCESS_TOKEN }}
          script: |
            const { data: commitList } = await github.pulls.listCommits({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number,
            });

            let prBody = '';
            let indentation = '';

            commitList.forEach(commit => {
              prBody += `${indentation}* ${commit.sha.substr(0, 7)} - **${commit.commit.message}**\n`;
              indentation += '\t';
            });

            const updateCommitListBody = `### 커밋 목록\n\n${prBody.trim()}\n\n---\n\n`

            const curBranch = context.payload.pull_request.head.ref;
            const updatedBranchBody = `### 반영 브랜치\n\n[${curBranch}](../tree/${curBranch}) -> [develop](../tree/develop)\n\n`;

            const separator = '### 변경 사항';
            const restOfBody = context.payload.pull_request.body.split(separator)[1];

            const updatedBody = `${updateCommitListBody}${updatedBranchBody}${restOfBody}`;

            await github.pulls.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number,
              body: updatedBody,
            });
